---
title: "国债期货利差交易"
author:
  - 陶成思
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---
```{r}
knitr::opts_chunk$set(warning = F, message = F)
```
## 环境设置
```{r}
# envrionment
rm(list=ls())
gc()

#读取包
library(dplyr)
library(zoo)
library(graphics)
library(ggplot2)
library(PerformanceAnalytics)
library(TTR)
library(lubridate)#判断第几周
```
##　计算合约每天的隐含收益率
```{r}
# 样本选取
# 提取T1509合约至T2106和TF1312至TF2106合约的最后交割日与所有可交割债券的代码，剩余期限，上一付息日，下一付息日，票面利率以及付息频率
data1 <- read.csv("TDInfo2020-11-16.csv")
#读取数据
head(data1)　
data1$LASTDELIVERY_DATE <- as.character(data1$LASTDELIVERY_DATE)
data1$LASTDELIVERY_DATE <- as.Date(paste(substr(data1$LASTDELIVERY_DATE,1,4),substr(data1$LASTDELIVERY_DATE,5,6),substr(data1$LASTDELIVERY_DATE,7,8),
                                         sep = '-'))
data1$anal_precupn <- as.Date(data1$anal_precupn)
data1$nxcupn <- as.Date(data1$nxcupn)
#由最后交割日推算出第二交割日，如果最后交割日是周一则天数减去3如果是其他天数则减去1，由于最后交易日是合约到期月份的第二个星期五，最后交割日为最后交易日后的第三个交易日，所以第二交割日为最后交易日后的第二个交易日，必然是周二或周三，所以直接在最后交割日减去一天即可。
data1 <- as.data.frame(data1 %>% mutate(SCDDELIVERY_DATE = LASTDELIVERY_DATE-1))
#提取所有合约的可交割债券的转换因子
data2 <- read.csv("CFInfo2020-11-16.csv")
head(data2)
data <- merge(data1,data2,by = c("sec_name","bond_cd"),all = TRUE)
#读取连续合约每日的收盘价和结算价，当十年期和五年期换月不一致时则统一。
data5 <- read.csv("ADPFutureClose2020-11-16.csv")
data5$date_id <- as.Date(data5$date_id)
data <- merge(data,data5,by = "sec_name", all = TRUE)
head(data)
#计算隐含收益率irr
data$irret <- NA
irr <- function(CouponRate,CF,PTMYear,SCDDeliveryDate,InterestfreQuency,SettlePrice,NXCUPN,ANAL_PRECUPN){
  # cf为现金流，可作为一个向量输入
  # CouponRate = data$couponrate[i]
  # CF = data$cf[i]
  # PTMYear=data$ptmyear[i]
  # SCDDeliveryDate = data$SCDDELIVERY_DATE[i]
  # InterestfreQuency = data$interestfrequency[i]
  # SettlePrice = data$settle[i]
  # NXCUPN = data$nxcupn[i]
  # ANAL_PRECUPN = data$anal_precupn[i]
  SecondDeliveryDate = SCDDeliveryDate
  cf = rep(CouponRate/InterestfreQuency,ceiling(PTMYear*InterestfreQuency))
  cf[length(cf)] = cf[length(cf)] + 100
  AI = CouponRate/InterestfreQuency*as.numeric(SecondDeliveryDate - ANAL_PRECUPN)/as.numeric(NXCUPN - ANAL_PRECUPN)
  PV = CF*SettlePrice+AI
  N <- length(cf) - 1
  n <- 0 : N
  f <- function(r, n) (1 + r/InterestfreQuency)^(n+as.numeric(NXCUPN-SecondDeliveryDate)/as.numeric(NXCUPN - ANAL_PRECUPN))
  r <- seq(0.0001,1,0.0001)
  pv <- cf / t(outer(r, n, f))
  npv <- colSums(pv)-PV
  irr <- r[abs(npv) == min(abs(npv))]
  return(irr)
}

for (i in c(1:length(data$sec_name))) {
  #i=1
  irret = irr(CouponRate = data$couponrate[i],CF = data$cf[i],PTMYear = data$ptmyear[i],
              SCDDeliveryDate = data$SCDDELIVERY_DATE[i],InterestfreQuency = data$interestfrequency[i],
              SettlePrice = data$settle[i],NXCUPN = data$nxcupn[i],ANAL_PRECUPN = data$anal_precupn[i])
  data$irret[i] = irret
}
data <- na.omit(data)
# 由于隐含收益率最小的债券一般是最廉可交割券，计算最廉，次廉和三廉券所对应的隐含收益率的平均值作为期货的隐含收益率
data <- as.data.frame(data %>% group_by(date_id,sec_name) %>% mutate(CTDRank = rank(irret,ties.method = c("first"))))
result <- aggregate(data = subset(data,CTDRank <= 3), irret~date_id+sec_name, mean)
# write.csv(result,'result.csv')
```

计算短期国债利率变动对整体利差变动的贡献率，以周作为频次。其中贡献率的计算公式为（贡献率=-2Y（5Y）国债收益率变动（BP）/利差变化（BP））。
```{r}
data <- read.csv("期限利差2020.csv")
data$DATE_ID <- as.Date(data$DATE_ID)
data$weeks <- paste0(year(data$DATE_ID),formatC(week(data$DATE_ID), flag = '0', width = 2))
table(data$weeks)
#按周数分组，由于需要涉及到前一周的利率数据，所以不能使用apply方法，只能使用FOR循环
data_week <- split(data,f = data$weeks)
data1 <- data.frame(WEEK_ID = names(data_week), contri_2 = NA, contri_5 = NA)
data1$contri_2[1] <- -(data_week[[1]]$R_2Y[4] - data_week[[1]]$R_2Y[1])*100/(data_week[[1]]$R_10Y_2Y[4] - data_week[[1]]$R_10Y_2Y[1])
for (i in (2:length(data_week))) {
  nrownow <- nrow(data_week[[i]])
  nrowpre <- nrow(data_week[[i-1]])
  data1$contri_2[i] <- -(data_week[[i]]$R_2Y[nrownow] - data_week[[i-1]]$R_2Y[nrowpre])*100/
    (data_week[[i]]$R_10Y_2Y[nrownow] - data_week[[i-1]]$R_10Y_2Y[nrowpre])
}
data1$contri_5[1] <- -(data_week[[1]]$R_5Y[4] - data_week[[1]]$R_5Y[1])*100/(data_week[[1]]$R_10Y_5Y[4] - data_week[[1]]$R_10Y_5Y[1])
for (i in (2:length(data_week))) {
  nrownow <- nrow(data_week[[i]])
  nrowpre <- nrow(data_week[[i-1]])
  data1$contri_5[i] <- -(data_week[[i]]$R_5Y[nrownow] - data_week[[i-1]]$R_5Y[nrowpre])*100/
    (data_week[[i]]$R_10Y_5Y[nrownow] - data_week[[i-1]]$R_10Y_5Y[nrowpre])
}
table(data1$contri_2 > 0.5)
table(data1$contri_5 > 0.5)
```




