---
title: "国债期货利差反转交易"
author:
  - 陶成思
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---
```{r}
knitr::opts_chunk$set(warning = F, message = F)
```
## 环境设置
```{r}
# envrionment
rm(list=ls())
gc()

#读取包
library(dplyr)
library(zoo)
library(graphics)
library(ggplot2)
library(PerformanceAnalytics)
library(TTR)
```



#反转策略设置止损
止损平仓的方式主要是基于净值的回撤，当原净值曲线回撤超过一定比例后，进行平仓。然而这一方式无法在后续回复期间获得收益。所以增加反抽开仓线。反抽开仓线有两种增加方式，一种是以隐含收益率序列回复作为反抽线。第二种方式是以假设按照原先的仓位继续持仓，当后续净值回复后再进行开仓操作。
为了方便验证，我们先使用第一种方式在全仓进行处理。
```{r}
#读取每日连续合约及其隐含收益率以及五年十年国债实际利差和隐含收益率利差
data1 <- read.csv("T_TFirret.csv")
# head(data1)
data1$date_id <- as.Date(data1$date_id)
data1 <- as.data.frame(data1 %>% mutate(quan90 = NA,quan80 = NA,quan70 = NA,quan60 = NA,quan50 = NA,
                                        quan40 = NA,quan30 = NA,quan20 = NA,quan10 = NA))
# 过去n个交易日的标准差的乘数作为分位点
n = 100
for (i in c(n:nrow(data1))) {
  data1$quan90[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*2+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan80[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*1.5+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan70[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*1+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan60[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*0.5+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan50[i] <- mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan40[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*(-0.5)+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan30[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*(-1)+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan20[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*(-1.5)+mean(data1$FutYHret[(i-n+1):(i-1)])
  data1$quan10[i] <- sd(data1$FutYHret[(i-n+1):(i-1)],na.rm = TRUE)*(-2)+mean(data1$FutYHret[(i-n+1):(i-1)])
}
data1 <- na.omit(data1)
# head(data1)
# data1 <- subset(data1,data1$date > as.Date('2015-10-21'))
# 读取国债期货收盘价和结算价
priceData <- read.csv("ADPFutureClose2020-09-16.csv")
#head(priceData)
priceData$date_id <- as.Date(priceData$date_id)
names(priceData)[5] <- "T_name"
data1 <- merge(data1,priceData,by = c("date_id","T_name"),all.x = TRUE)
data1 <- data1[,c("date_id","T_name","T_irret","close","settle","TF_name","TF_irret","FutYHret",
                  "quan90","quan80","quan70","quan60","quan50","quan40","quan30","quan20","quan10")]
names(data1)[4:5] <- c("T_close","T_settle")
names(priceData)[5] <- "TF_name"    
data1 <- merge(data1,priceData,by = c("date_id","TF_name"),all.x = TRUE)
data1 <- data1[,c("date_id","T_name","T_irret","T_close","T_settle","TF_name","TF_irret","close","settle","FutYHret",
                  "quan90","quan80","quan70","quan60","quan50","quan40","quan30","quan20","quan10")]
names(data1)[8:9] <- c("TF_close","TF_settle")
```

```{r}
data1 <- as.data.frame(data1 %>% mutate(upDown90 = ifelse(FutYHret >= quan90, 1,ifelse(FutYHret <= quan10, -1, NA)),
                                        upDown80 = ifelse(FutYHret >= quan80, 1,ifelse(FutYHret <= quan20, -1, NA)),
                                        upDown70 = ifelse(FutYHret >= quan70, 1,ifelse(FutYHret <= quan30, -1, NA)),
                                        upDown60 = ifelse(FutYHret >= quan60, 1,ifelse(FutYHret <= quan40, -1, NA))))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret > quan10 & FutYHret <= quan50,-1,0),
                                        position_TF90 = ifelse(FutYHret > quan10 & FutYHret <= quan50,2,0),
                                        position_T80 = ifelse(FutYHret > quan20 & FutYHret <= quan50,-1,0),
                                        position_TF80 = ifelse(FutYHret > quan20 & FutYHret <= quan50,2,0),
                                        position_T70 = ifelse(FutYHret > quan30 & FutYHret <= quan50,-1,0),
                                        position_TF70 = ifelse(FutYHret > quan30 & FutYHret <= quan50,2,0),
                                        position_T60 = ifelse(FutYHret > quan40 & FutYHret <= quan50,-1,0),
                                        position_TF60 = ifelse(FutYHret > quan40 & FutYHret <= quan50,2,0)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret < quan90 & FutYHret > quan50,1,position_T90),
                                        position_TF90 = ifelse(FutYHret < quan90 & FutYHret > quan50,-2,position_TF90),
                                        position_T80 = ifelse(FutYHret < quan80 & FutYHret > quan50,1,position_T80),
                                        position_TF80 = ifelse(FutYHret < quan80 & FutYHret > quan50,-2,position_TF80),
                                        position_T70 = ifelse(FutYHret < quan70 & FutYHret > quan50,1,position_T70),
                                        position_TF70 = ifelse(FutYHret < quan70 & FutYHret > quan50,-2,position_TF70),
                                        position_T60 = ifelse(FutYHret < quan60 & FutYHret > quan50,1,position_T60),
                                        position_TF60 = ifelse(FutYHret < quan60 & FutYHret > quan50,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(upDown90 = ifelse(abs(position_T90 - dplyr::lag(position_T90))==2 & is.na(upDown90),0,upDown90),
                                        upDown80 = ifelse(abs(position_T80 - dplyr::lag(position_T80))==2 & is.na(upDown80),0,upDown80),
                                        upDown70 = ifelse(abs(position_T70 - dplyr::lag(position_T70))==2 & is.na(upDown70),0,upDown70),
                                        upDown60 = ifelse(abs(position_T60 - dplyr::lag(position_T60))==2 & is.na(upDown60),0,upDown60)))
data1 <- as.data.frame(data1 %>% mutate(upDown90 = na.locf0(upDown90),upDown80 = na.locf0(upDown80),
                                        upDown70 = na.locf0(upDown70),upDown60 = na.locf0(upDown60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(upDown90 == -1 & FutYHret > quan10 & FutYHret <= quan50,-1,0),
                                        position_TF90 = ifelse(upDown90 == -1 & FutYHret > quan10 & FutYHret <= quan50,2,0),
                                        position_T80 = ifelse(upDown80 == -1 & FutYHret > quan20 & FutYHret <= quan50,-1,0),
                                        position_TF80 = ifelse(upDown80 == -1 & FutYHret > quan20 & FutYHret <= quan50,2,0),
                                        position_T70 = ifelse(upDown70 == -1 & FutYHret > quan30 & FutYHret <= quan50,-1,0),
                                        position_TF70 = ifelse(upDown70 == -1 & FutYHret > quan30 & FutYHret <= quan50,2,0),
                                        position_T60 = ifelse(upDown60 == -1 & FutYHret > quan40 & FutYHret <= quan50,-1,0),
                                        position_TF60 = ifelse(upDown60 == -1 & FutYHret > quan40 & FutYHret <= quan50,2,0)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(upDown90 == 1 & FutYHret < quan90 & FutYHret > quan50,1,position_T90),
                                        position_TF90 = ifelse(upDown90 == 1 & FutYHret < quan90 & FutYHret > quan50,-2,position_TF90),
                                        position_T80 = ifelse(upDown80 == 1 & FutYHret < quan80 & FutYHret > quan50,1,position_T80),
                                        position_TF80 = ifelse(upDown80 == 1 & FutYHret < quan80 & FutYHret > quan50,-2,position_TF80),
                                        position_T70 = ifelse(upDown70 == 1 & FutYHret < quan70 & FutYHret > quan50,1,position_T70),
                                        position_TF70 = ifelse(upDown70 == 1 & FutYHret < quan70 & FutYHret > quan50,-2,position_TF70),
                                        position_T60 = ifelse(upDown60 == 1 & FutYHret < quan60 & FutYHret > quan50,1,position_T60),
                                        position_TF60 = ifelse(upDown60 == 1 & FutYHret < quan60 & FutYHret > quan50,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret >= quan90,1,position_T90),
                                        position_TF90 = ifelse(FutYHret >= quan90,-2,position_TF90),
                                        position_T80 = ifelse(FutYHret >= quan80,1,position_T80),
                                        position_TF80 = ifelse(FutYHret >= quan80,-2,position_TF80),
                                        position_T70 = ifelse(FutYHret >= quan70,1,position_T70),
                                        position_TF70 = ifelse(FutYHret >= quan70,-2,position_TF70),
                                        position_T60 = ifelse(FutYHret >= quan60,1,position_T60),
                                        position_TF60 = ifelse(FutYHret >= quan60,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret <= quan10,-1,position_T90),
                                        position_TF90 = ifelse(FutYHret <= quan10,2,position_TF90),
                                        position_T80 = ifelse(FutYHret <= quan20,-1,position_T80),
                                        position_TF80 = ifelse(FutYHret <= quan20,2,position_TF80),
                                        position_T70 = ifelse(FutYHret <= quan30,-1,position_T70),
                                        position_TF70 = ifelse(FutYHret <= quan30,2,position_TF70),
                                        position_T60 = ifelse(FutYHret <= quan40,-1,position_T60),
                                        position_TF60 = ifelse(FutYHret <= quan40,2,position_TF60)))
```

```{r}
steps = 2
data1 <- as.data.frame(data1 %>% mutate(position_T = position_T90+position_T70,
                                        position_TF = position_TF90+position_TF70))
data1$lag_position_T <- lag(data1$position_T)
data1$lag_position_TF <- lag(data1$position_TF)
data1 <- as.data.frame(data1 %>% mutate(lag_position_T = ifelse(is.na(lag_position_T),0,lag_position_T),
                                        lag_position_TF = ifelse(is.na(lag_position_TF),0,lag_position_TF)))
# data1 <- subset(data1,date_id < as.Date("2020-01-01"))
#计算合约开仓时账户金额
data1$ZHJE <- 1000000
#计算合约开仓手数
data1$KCSS <- 0
#计算闲置资金占比
data1$XZZJ <- 0
#加入止损策略，在组合的净值基础性加入回撤，将回撤平仓线和反抽开仓线分别设置为10%和20%。
#其中回撤平仓线是指当组合的净值在本次开仓后最大回撤大于15%时则平仓，平仓后如果此时虚拟持仓的净值较平仓时的值与平仓后至今最低点的值回升了20%，且还满足开仓条件则再次开仓。
#计算每一次的开仓点位后的回撤
data1$Drawdowns = 0
#需要用到两个变量，当前交易下的期间最大的净值和最大净值之后出现的最小净值
data1$MAXJZ = 0
data1$MINJZ = 0
#判断是否是最大净值之后需要辅助变量
data1$ismax = 0
#平仓后计算虚拟持仓以计算反抽收益
data1$XNJZ = 1000000
#平仓后计算反抽收益
data1$FCSY = 0
# data1 <- subset(data1,data1$date_id < as.Date('2020-01-01'))
zhisunxian <- 0.10
fanchouxian <- 0.20
#增加辅助变量，当实际开仓为1时，账户净值开仓，当实际开仓为0时，账户净值不开仓。
data1$SJKC <- NA
#计算
for (i in c(2:length(data1$date_id))) {
  # i=35
  #开仓前
  if(data1$lag_position_T[i-1]==0 & data1$lag_position_T[i]!=0){
    data1$KCSS[i] = floor(data1$ZHJE[i-1]/(max(2*0.012*data1$TF_settle[i-1]*10000,0.02*data1$T_settle[i-1]*10000)*steps))
    data1$ZHJE[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_settle[i]-data1$T_settle[i-1])+
                    10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_settle[i]-data1$TF_settle[i-1]) + data1$ZHJE[i-1]
    data1$MAXJZ[i] = max(data1$MAXJZ[i-1],data1$ZHJE[i])
    data1$MINJZ[i] = min(data1$MINJZ[i-1],data1$ZHJE[i])
    data1$XNJZ[i] = data1$ZHJE[i]
    if(data1$MAXJZ[i] > data1$ZHJE[i]){data1$ismax[i] = 1}
    data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
    data1$SJKC[i] = 1
    }
  else{
    #有仓位
    if(data1$lag_position_T[i-1]!=0 & data1$lag_position_T[i]!=0){
      data1$KCSS[i] = data1$KCSS[i-1]
      data1$XNJZ[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_settle[i]-data1$T_settle[i-1])+
          10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_settle[i]-data1$TF_settle[i-1]) + data1$XNJZ[i-1]
      data1$MAXJZ[i] = max(data1$MAXJZ[i-1],data1$XNJZ[i])
      if(data1$MAXJZ[i] > data1$XNJZ[i]){data1$ismax[i] = 1}
      if(data1$ismax[i] == 0){
        #data1$MAXJZ[i] = max(data1$MAXJZ[i-1],data1$XNJZ[i])
        #if(data1$MAXJZ[i] > data1$XNJZ[i]){data1$ismax[i] = 1}
        data1$MINJZ[i] = data1$XNJZ[i]
        data1$ZHJE[i] = data1$XNJZ[i]
        data1$Drawdowns[i] = (data1$MAXJZ[i] - data1$MINJZ[i])/data1$MAXJZ[i]
        data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
        data1$SJKC[i] = 1
      }
      if(data1$ismax[i]==1){
        data1$MINJZ[i] = min(data1$MINJZ[i-1],data1$XNJZ[i])
        data1$Drawdowns[i] = (data1$MAXJZ[i] - data1$MINJZ[i])/data1$MAXJZ[i]
        #data1$FCSY[i] = (data1$XNJZ[i]-data1$MINJZ[i])/abs(data1$MINJZ[i])
        data1$FCSY[i] = (data1$MAXJZ[i]-data1$MINJZ[i])*fanchouxian+data1$MINJZ[i]
        if(data1$Drawdowns[i-1]>zhisunxian & data1$XNJZ[i] < data1$FCSY[i] & data1$SJKC[i-1] == 0){
          data1$ZHJE[i] = data1$ZHJE[i-1]
          data1$XZZJ[i] = 1
          data1$SJKC[i] = 0
          }
        else{
          if(data1$Drawdowns[i-1]>zhisunxian & data1$XNJZ[i] >= data1$FCSY[i] & data1$SJKC[i-1] == 0){
            data1$KCSS[i] = floor(data1$ZHJE[i-1]/(max(2*0.012*data1$TF_settle[i-1]*10000,0.02*data1$T_settle[i-1]*10000)*steps))
            #data1$ZHJE[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_settle[i]-data1$T_settle[i-1])+
              #10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_settle[i]-data1$TF_settle[i-1]) + data1$ZHJE[i-1]
            data1$ZHJE[i] = data1$ZHJE[i-1]
            data1$XNJZ[i] = data1$ZHJE[i]
            data1$ismax[i] = 0
            data1$MAXJZ[i] = data1$ZHJE[i]
            data1$MINJZ[i] = data1$ZHJE[i]
            data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
            data1$SJKC[i] = 1
            }
          else{
            if(data1$Drawdowns[i-1]>zhisunxian & data1$XNJZ[i] > data1$FCSY[i] & data1$SJKC[i-1] == 1){
              data1$ZHJE[i] = data1$ZHJE[i-1]
              data1$XZZJ[i] = 1
              data1$SJKC[i] = 0
            }
            else{
              data1$ZHJE[i] = data1$XNJZ[i]
              data1$XZZJ[i] = (data1$ZHJE[i] -
                       data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
            data1$SJKC[i] = 0
            }
          }
        }
      }
    }
    #无仓位
    else{
      data1$KCSS[i] = 0
      data1$ZHJE[i] = data1$ZHJE[i-1]
      data1$XNJZ[i] = data1$ZHJE[i-1]
      data1$MAXJZ[i] = data1$ZHJE[i]
      data1$MINJZ[i] = data1$ZHJE[i]
      data1$XZZJ[i] = 1
      data1$SJKC[i] = 0
    }
  }
}

ggplot(data = data1,aes(date_id,ZHJE)) + geom_line()
data1$date_id <- as.Date(data1$date_id)
data1$return <- data1$ZHJE/lag(data1$ZHJE)-1
data1$return[1] <- 0
mean(data1$XZZJ)
maxDrawdown(data1$return)
Return.annualized(data1$return,scale = 252)
write.csv(data1,"data1.csv")
#write.csv(data1[c('date_id','T_name','TF_name','FutYHret','quan90','quan50','quan10','lag_position_T','lag_position_TF','ZHJE','XNJZ','KCSS','XZZJ',
                  #'Drawdowns','MAXJZ','MINJZ','ismax','FCSY','return')],"data1.csv")
```

