---
title: "国债期货利差反转交易"
author:
  - 陶成思
documentclass: ctexart
output:
  rticles::ctex:
    fig_caption: yes
    number_sections: yes
    toc: yes
classoption: "hyperref,"
---
```{r}
knitr::opts_chunk$set(warning = F, message = F)
```
## 环境设置
```{r}
# envrionment
rm(list=ls())
gc()

#读取包
library(dplyr)
library(zoo)
library(graphics)
library(ggplot2)
library(PerformanceAnalytics)
library(TTR)
```

## R Markdown

#反转策略设置止损
止损平仓的方式主要是基于净值的回撤，当原净值曲线回撤超过一定比例后，进行平仓。然而这一方式无法在后续回复期间获得收益。假设按照原先的仓位继续持仓，当净值回复后在继续持仓。reverseTRADE2与reverseTRADE的不同之处在于reverseTRADE2的反抽开仓线，即本次交易的最大净值和最小净值的差额的百分比（例如20%）加上最小净值。
```{r}
#读取每日连续合约及其隐含收益率以及五年十年国债实际利差和隐含收益率利差
data1 <- read.csv("T_TFirret.csv")
# head(data1)
data1$date_id <- as.Date(data1$date_id)
data1 <- as.data.frame(data1 %>% mutate(quan90 = NA,quan80 = NA,quan70 = NA,quan60 = NA,quan50 = NA,
                                        quan40 = NA,quan30 = NA,quan20 = NA,quan10 = NA))
# 过去n个交易日的不同分位点作为曲线交易的判断依据
n = 100
for (i in c(n:nrow(data1))) {
  data1$quan90[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.9, na.rm = TRUE)
  data1$quan80[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.8, na.rm = TRUE)
  data1$quan70[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.7, na.rm = TRUE)
  data1$quan60[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.6, na.rm = TRUE)
  data1$quan50[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.5, na.rm = TRUE)
  data1$quan40[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.4, na.rm = TRUE)
  data1$quan30[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.3, na.rm = TRUE)
  data1$quan20[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.2, na.rm = TRUE)
  data1$quan10[i] <- quantile(data1$FutYHret[(i-n):(i-1)], 0.1, na.rm = TRUE)
}
data1 <- na.omit(data1)
# head(data1)
# data1 <- subset(data1,data1$date > as.Date('2015-10-21'))
# 读取国债期货收盘价和结算价
priceData <- read.csv("ADPFutureClose2020-09-16.csv")
#head(priceData)
priceData$date_id <- as.Date(priceData$date_id)
names(priceData)[5] <- "T_name"
data1 <- merge(data1,priceData,by = c("date_id","T_name"),all.x = TRUE)
data1 <- data1[,c("date_id","T_name","T_irret","close","settle","TF_name","TF_irret","FutYHret",
                  "quan90","quan80","quan70","quan60","quan50","quan40","quan30","quan20","quan10")]
names(data1)[4:5] <- c("T_close","T_settle")
names(priceData)[5] <- "TF_name"    
data1 <- merge(data1,priceData,by = c("date_id","TF_name"),all.x = TRUE)
data1 <- data1[,c("date_id","T_name","T_irret","T_close","T_settle","TF_name","TF_irret","close","settle","FutYHret",
                  "quan90","quan80","quan70","quan60","quan50","quan40","quan30","quan20","quan10")]
names(data1)[8:9] <- c("TF_close","TF_settle")
```

```{r}
data1 <- as.data.frame(data1 %>% mutate(upDown90 = ifelse(FutYHret >= quan90, 1,ifelse(FutYHret <= quan10, -1, NA)),
                                        upDown80 = ifelse(FutYHret >= quan80, 1,ifelse(FutYHret <= quan20, -1, NA)),
                                        upDown70 = ifelse(FutYHret >= quan70, 1,ifelse(FutYHret <= quan30, -1, NA)),
                                        upDown60 = ifelse(FutYHret >= quan60, 1,ifelse(FutYHret <= quan40, -1, NA))))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret > quan10 & FutYHret <= quan50,-1,0),
                                        position_TF90 = ifelse(FutYHret > quan10 & FutYHret <= quan50,2,0),
                                        position_T80 = ifelse(FutYHret > quan20 & FutYHret <= quan50,-1,0),
                                        position_TF80 = ifelse(FutYHret > quan20 & FutYHret <= quan50,2,0),
                                        position_T70 = ifelse(FutYHret > quan30 & FutYHret <= quan50,-1,0),
                                        position_TF70 = ifelse(FutYHret > quan30 & FutYHret <= quan50,2,0),
                                        position_T60 = ifelse(FutYHret > quan40 & FutYHret <= quan50,-1,0),
                                        position_TF60 = ifelse(FutYHret > quan40 & FutYHret <= quan50,2,0)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret < quan90 & FutYHret > quan50,1,position_T90),
                                        position_TF90 = ifelse(FutYHret < quan90 & FutYHret > quan50,-2,position_TF90),
                                        position_T80 = ifelse(FutYHret < quan80 & FutYHret > quan50,1,position_T80),
                                        position_TF80 = ifelse(FutYHret < quan80 & FutYHret > quan50,-2,position_TF80),
                                        position_T70 = ifelse(FutYHret < quan70 & FutYHret > quan50,1,position_T70),
                                        position_TF70 = ifelse(FutYHret < quan70 & FutYHret > quan50,-2,position_TF70),
                                        position_T60 = ifelse(FutYHret < quan60 & FutYHret > quan50,1,position_T60),
                                        position_TF60 = ifelse(FutYHret < quan60 & FutYHret > quan50,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(upDown90 = ifelse(abs(position_T90 - dplyr::lag(position_T90))==2 & is.na(upDown90),0,upDown90),
                                        upDown80 = ifelse(abs(position_T80 - dplyr::lag(position_T80))==2 & is.na(upDown80),0,upDown80),
                                        upDown70 = ifelse(abs(position_T70 - dplyr::lag(position_T70))==2 & is.na(upDown70),0,upDown70),
                                        upDown60 = ifelse(abs(position_T60 - dplyr::lag(position_T60))==2 & is.na(upDown60),0,upDown60)))
data1 <- as.data.frame(data1 %>% mutate(upDown90 = na.locf0(upDown90),upDown80 = na.locf0(upDown80),
                                        upDown70 = na.locf0(upDown70),upDown60 = na.locf0(upDown60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(upDown90 == -1 & FutYHret > quan10 & FutYHret <= quan50,-1,0),
                                        position_TF90 = ifelse(upDown90 == -1 & FutYHret > quan10 & FutYHret <= quan50,2,0),
                                        position_T80 = ifelse(upDown80 == -1 & FutYHret > quan20 & FutYHret <= quan50,-1,0),
                                        position_TF80 = ifelse(upDown80 == -1 & FutYHret > quan20 & FutYHret <= quan50,2,0),
                                        position_T70 = ifelse(upDown70 == -1 & FutYHret > quan30 & FutYHret <= quan50,-1,0),
                                        position_TF70 = ifelse(upDown70 == -1 & FutYHret > quan30 & FutYHret <= quan50,2,0),
                                        position_T60 = ifelse(upDown60 == -1 & FutYHret > quan40 & FutYHret <= quan50,-1,0),
                                        position_TF60 = ifelse(upDown60 == -1 & FutYHret > quan40 & FutYHret <= quan50,2,0)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(upDown90 == 1 & FutYHret < quan90 & FutYHret > quan50,1,position_T90),
                                        position_TF90 = ifelse(upDown90 == 1 & FutYHret < quan90 & FutYHret > quan50,-2,position_TF90),
                                        position_T80 = ifelse(upDown80 == 1 & FutYHret < quan80 & FutYHret > quan50,1,position_T80),
                                        position_TF80 = ifelse(upDown80 == 1 & FutYHret < quan80 & FutYHret > quan50,-2,position_TF80),
                                        position_T70 = ifelse(upDown70 == 1 & FutYHret < quan70 & FutYHret > quan50,1,position_T70),
                                        position_TF70 = ifelse(upDown70 == 1 & FutYHret < quan70 & FutYHret > quan50,-2,position_TF70),
                                        position_T60 = ifelse(upDown60 == 1 & FutYHret < quan60 & FutYHret > quan50,1,position_T60),
                                        position_TF60 = ifelse(upDown60 == 1 & FutYHret < quan60 & FutYHret > quan50,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret >= quan90,1,position_T90),
                                        position_TF90 = ifelse(FutYHret >= quan90,-2,position_TF90),
                                        position_T80 = ifelse(FutYHret >= quan80,1,position_T80),
                                        position_TF80 = ifelse(FutYHret >= quan80,-2,position_TF80),
                                        position_T70 = ifelse(FutYHret >= quan70,1,position_T70),
                                        position_TF70 = ifelse(FutYHret >= quan70,-2,position_TF70),
                                        position_T60 = ifelse(FutYHret >= quan60,1,position_T60),
                                        position_TF60 = ifelse(FutYHret >= quan60,-2,position_TF60)))
data1 <- as.data.frame(data1 %>% mutate(position_T90 = ifelse(FutYHret <= quan10,-1,position_T90),
                                        position_TF90 = ifelse(FutYHret <= quan10,2,position_TF90),
                                        position_T80 = ifelse(FutYHret <= quan20,-1,position_T80),
                                        position_TF80 = ifelse(FutYHret <= quan20,2,position_TF80),
                                        position_T70 = ifelse(FutYHret <= quan30,-1,position_T70),
                                        position_TF70 = ifelse(FutYHret <= quan30,2,position_TF70),
                                        position_T60 = ifelse(FutYHret <= quan40,-1,position_T60),
                                        position_TF60 = ifelse(FutYHret <= quan40,2,position_TF60)))
```

```{r}
steps = 4
data1 <- as.data.frame(data1 %>% mutate(position_T = position_T90+position_T80+position_T70+position_T60,
                                        position_TF = position_TF90+position_TF80+position_TF70+position_TF60))
data1$lag_position_T <- lag(data1$position_T)
data1$lag_position_TF <- lag(data1$position_TF)
data1 <- as.data.frame(data1 %>% mutate(lag_position_T = ifelse(is.na(lag_position_T),0,lag_position_T),
                                        lag_position_TF = ifelse(is.na(lag_position_TF),0,lag_position_TF)))
# data1 <- subset(data1,date_id < as.Date("2020-01-01"))
#计算合约开仓时账户金额
data1$lag_position_T_ZS <- lag(data1$position_T)
data1$lag_position_TF_ZS <- lag(data1$position_TF)
data1$ZHJE <- 1000000
#计算合约开仓手数
data1$KCSS <- 0
#计算闲置资金占比
data1$XZZJ <- 0
#加入止损策略，在组合的净值基础性加入回撤，将回撤平仓线和反抽开仓线分别设置为10%和20%。
#其中回撤平仓线是指当组合的净值在本次开仓后最大回撤大于15%时则平仓，平仓后如果此时虚拟持仓的净值较平仓时的值与平仓后至今最低点的值回升了20%，且还满足开仓条件则再次开仓。
#计算每一次的开仓点位后的回撤
data1$Drawdowns = 0
#需要用到两个变量，当前交易下的期间最大的净值和最大净值之后出现的最小净值
data1$MAXJZ = 0
data1$MINJZ = 0
#判断是否是最大净值之后需要辅助变量
data1$ismax = 0
#平仓后计算虚拟持仓以计算反抽收益
data1$XNJZ = 1000000
#平仓后计算反抽收益
data1$FCSY = 0
#data1 <- subset(data1,data1$date_id < as.Date('2020-01-01'))
zhisunxian <- 0.05
fanchouxian <- 0.20
#计算
for (i in c(2:length(data1$date_id))) {
  # i=51
  # 开仓首日
  if((data1$lag_position_T[i-1]==0 & data1$lag_position_T[i]!=0) | (data1$lag_position_T[i-1]*data1$lag_position_T[i]<0)){
    # 开仓手数以昨日真实账户净值和前一日的收盘价作为开仓手数（早盘开仓）
    data1$KCSS[i] = floor(data1$ZHJE[i-1]/(max(2*0.012*data1$TF_close[i-1]*10000,0.02*data1$T_close[i-1]*10000)*steps))
    # 今日收盘后的账户资金
    data1$ZHJE[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_close[i]-data1$T_close[i-1])+
                    10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_close[i]-data1$TF_close[i-1]) + data1$ZHJE[i-1]
    # 最大净值为前一日最大资金和今日账户资金最大值
    data1$MAXJZ[i] = max(data1$MAXJZ[i-1],data1$ZHJE[i])
    data1$MINJZ[i] = data1$ZHJE[i]
    # 首日开仓将账户资金的值赋予虚拟账户的净值
    data1$XNJZ[i] = data1$ZHJE[i]
    # 如果最大净值出现在过去，也就是首日亏损，则ismax=1
    if(data1$MAXJZ[i] > data1$ZHJE[i]){data1$ismax[i] = 1}
     # 计算闲置资金
    data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_close[i]*10000,0.02*data1$T_close[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
    }
  else{
    # 非首日开仓
    if(data1$lag_position_T[i-1]*data1$lag_position_T[i]>0){
      # 顺眼上一日的持仓手数
      data1$KCSS[i] = data1$KCSS[i-1]
      # 不确定真实账户是否开仓，用虚拟账户计算账户今日收盘后的净值
      data1$XNJZ[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_close[i]-data1$T_close[i-1])+
          10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_close[i]-data1$TF_close[i-1]) + data1$XNJZ[i-1]
      data1$MAXJZ[i] = max(data1$MAXJZ[i-1],data1$XNJZ[i])
      # 如果最大净值发生在今日之前，则今日的ismax为1
      if(data1$MAXJZ[i] > data1$XNJZ[i]){data1$ismax[i] = 1}
      
       ## 如果最大净值发生在当日，且不处于平仓状态，最小净值等于XNJZ  即只有在开仓状态下且最大净值发生在今日才有MINJZ=XNJZ,MAXJZ=XNJZ
      if(data1$ismax[i] == 0 & data1$lag_position_T_ZS[i-1]!=0){data1$MINJZ[i] = data1$XNJZ[i]}
      else{data1$MINJZ[i] = min(data1$MINJZ[i-1],data1$XNJZ[i])}
      
      # 最大回撤为当日最大净值与最小净值的差处于最大净值
      data1$Drawdowns[i] = (data1$MAXJZ[i] - data1$MINJZ[i])/data1$MAXJZ[i]
            # 反抽收益为虚拟净值与最小净值的涨幅
      data1$FCSY[i] = (data1$MAXJZ[i]-data1$MINJZ[i])*fanchouxian + data1$MINJZ[i]

            # 如果前一天最大回撤大于10%反抽收益小于20%，那么账户净值不变（因为不会真实交易），闲置资金率为100%
      if(data1$Drawdowns[i-1]>zhisunxian & data1$XNJZ[i-1]<data1$FCSY[i-1]){
          data1$ZHJE[i] = data1$ZHJE[i-1]
          data1$XZZJ[i] = 1
          data1$lag_position_T_ZS[i] = 0
          data1$lag_position_TF_ZS[i] = 0
          }
      else{
            # 如果前一日反抽收益大于20%，无论最大回撤为多少
            if((data1$XNJZ[i-1]>=data1$FCSY[i-1]) & data1$lag_position_T_ZS[i-1]==0){
            # 重新开仓，计算前一日的真实账户资金以上一日结算价可以开仓多少手
            data1$KCSS[i] = floor(data1$ZHJE[i-1]/(max(2*0.012*data1$TF_settle[i-1]*10000,0.02*data1$T_settle[i-1]*10000)*steps))
            # 早盘以上一日结算价开仓，当日收盘后账户净值
            data1$ZHJE[i] = 10000*data1$KCSS[i]*data1$lag_position_T[i]*(data1$T_settle[i]-data1$T_settle[i-1])+
              10000*data1$KCSS[i]*data1$lag_position_TF[i]*(data1$TF_settle[i]-data1$TF_settle[i-1]) + data1$ZHJE[i-1]
            # data1$ZHJE[i] = data1$ZHJE[i-1] # 由于近日开仓，所以账户资金和上一日相同
            # 此时虚拟账户得值归为账户资金的值
            
            data1$XNJZ[i] = data1$ZHJE[i]
            # 新一轮开仓
            #data1$ismax[i] = 0
            #data1$MAXJZ[i] = data1$ZHJE[i]
            data1$MINJZ[i] = data1$ZHJE[i]
            data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
            }
          else{
            data1$ZHJE[i] = data1$XNJZ[i]
            data1$XZZJ[i] = (data1$ZHJE[i] - data1$KCSS[i]*max(2*0.012*data1$TF_settle[i]*10000,0.02*data1$T_settle[i]*10000)*abs(data1$lag_position_T[i]))/data1$ZHJE[i]
          }
        }
      }
    #无仓位
    else{
      data1$KCSS[i] = 0
      data1$ZHJE[i] = data1$ZHJE[i-1]
      data1$XNJZ[i] = data1$ZHJE[i-1]
      data1$MAXJZ[i] = data1$ZHJE[i]
      data1$MINJZ[i] = data1$ZHJE[i]
      data1$XZZJ[i] = 1
    }
  }
}

ggplot(data = data1,aes(date_id,ZHJE)) + geom_line()
data1$date_id <- as.Date(data1$date_id)
data1$return <- data1$ZHJE/lag(data1$ZHJE)-1
data1$return[1] <- 0
mean(data1$XZZJ)
maxDrawdown(data1$return)
Return.annualized(data1$return,scale = 252)
write.csv(data1,"data1.csv")
#write.csv(data1[c('date_id','T_name','TF_name','FutYHret','quan90','quan50','quan10','lag_position_T','lag_position_TF','ZHJE','XNJZ','KCSS','XZZJ',
                  #'Drawdowns','MAXJZ','MINJZ','ismax','FCSY','return')],"data1.csv")
```

